chimera: fix FsInode_CONST#stat()
CONST is a syntetic inode and need full set of
attributes.

Inherit most of them from the parent directory and
adjust required bits. Fixes stacktrace:

06 Jul 2015 06:33:21 (NFS-dcache-lab007) [] Unhandled exception:
com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Attribute is not defined: GID
	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
	at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
	...

Acked-by: Gerd Behrmann
Target: master
Require-book: no
Require-notes: no