pool: Fix regression breaking hopping mananger
Motivation:

When setting pool.destination.replication, pools generate the error:

01 Apr 2016 19:23:24 (pool73_1) [] Unexpected failure during state change notification
java.lang.IllegalArgumentException: Required attributes are missing.
    at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~[guava-18.0.jar:na]
    at diskCacheV111.vehicles.PoolMgrGetPoolMsg.<init>(PoolMgrGetPoolMsg.java:27) ~[dcache-vehicles-2.13.28.jar:2.13.28]
    at diskCacheV111.vehicles.PoolMgrSelectPoolMsg.<init>(PoolMgrSelectPoolMsg.java:37) ~[dcache-core-2.13.28.jar:2.13.28]
    at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:81) ~[dcache-core-2.13.28.jar:2.13.28]
    at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:67) ~[dcache-core-2.13.28.jar:2.13.28]
    at diskCacheV111.vehicles.PoolMgrReplicateFileMsg.<init>(PoolMgrReplicateFileMsg.java:25) ~[dcache-core-2.13.28.jar:2.13.28]
    at org.dcache.pool.classic.PoolV4$ReplicationHandler._initiateReplication(PoolV4.java:844) ~[dcache-core-2.13.28.jar:2.13.28]
    at org.dcache.pool.classic.PoolV4$ReplicationHandler.initiateReplication(PoolV4.java:815) ~[dcache-core-2.13.28.jar:2.13.28]
    at org.dcache.pool.classic.PoolV4$ReplicationHandler.stateChanged(PoolV4.java:792) ~[dcache-core-2.13.28.jar:2.13.28]
    at org.dcache.pool.repository.v5.StateChangeListeners.lambda$stateChanged$32(StateChangeListeners.java:66) ~[dcache-core-2.13.28.jar:2.13.28]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_77]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_77]
    at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_77]

Modification:

Inject the missing attribute in the message. Adjust pre-condition in the
message since there is a difference between required attributes and used
attributes as the P2P companion fetches missing attributes. This is important
for this feature as there is no guarantee that the pool has a cached copy of
the checkum.

Result:

Fixes a regression in pools causing it to fail with an IllegalArgumentException
when replication manager is enabled.

Target: trunk
Require-notes: yes
Require-book: no
Request: 2.15
Request: 2.14
Request: 2.13
Request: 2.12
Ticket: http://rt.dcache.org/Ticket/Display.html?id=8938

Reviewed at https://rb.dcache.org/r/9166/

(cherry picked from commit 6c344851c7835fdb641a2d6cd3dda2dfc1216819)
(cherry picked from commit 0aa69547ac56089a7330c42c6493afcd5d184453)