ChimeraCleaner: reallow to be compiled/run on different Java versions
Return class of ConcurrentHashMap.keySet() was changed from Set() in
Java <= 7 to ConcurrentHashMap.KeySetView in Java 8,
  http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ConcurrentHashMap.html#keySet%28%29
  https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/ConcurrentHashMap.html#keySet--
and old method signature wasn't preserved.

So, anything compiled with Java 8 will throw an exception with
Java 7 runtime like
{{{
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView
;
        at org.dcache.chimera.namespace.ChimeraCleaner.ac_ls_blacklist(ChimeraCleaner.java:651) ~[dcache-chimera-2.10.41.jar:2
.10.41]
}}}

And such exception will terminate the current and subsequent executions
of the run() method, as warranted by
SheduledExecutorService.scheduleWithFixedDelay(),
  https://docs.oracle.com/javase/7/docs/api/java/util/concurrent/ScheduledExecutorService.html#scheduleWithFixedDelay%28java.lang.Runnable,%20long,%20long,%20java.util.concurrent.TimeUnit%29

Also, give a meaningful notification on an similar exception:
cleaner will still be stopped, but admins will know the reason
and will be able to inform developers and provide at least stack
trace.

Signed-off-by: Eygene Ryabinkin <rea@grid.kiae.ru>
Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>