webdav: fix java.lang.ClassCastException: error
Motivation

fix:

02 May 2018 13:08:06 (WebDAV-dcache-lab000) [door:WebDAV-dcache-lab000@web:AAVrNxnsb2A dcache-lab002-A DoorTransferFinished 000022D2361B15464A809E397D48F34DAB22] Uncaught exception in thread WebDAV-dcache-lab000-0
org.apache.kafka.common.errors.SerializationException: Can't convert value of class diskCacheV111.vehicles.DoorRequestInfoMessage to class org.dcache.notification.BillingMessageSerializer specified in value.serializer
java.lang.ClassCastException: diskCacheV111.vehicles.DoorRequestInfoMessage cannot be cast to diskCacheV111.vehicles.MoverInfoMessage
    at org.dcache.notification.BillingMessageSerializer.serialize(BillingMessageSerializer.java:16) ~[dcache-core-4.2.0-SNAPSHOT.jar:4.2.0-SNAPSHOT]
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:65) ~[kafka-clients-1.0.0.jar:na]
    at org.apache.kafka.common.serialization.ExtendedSerializer$Wrapper.serialize(ExtendedSerializer.java:55) ~[kafka-clients-1.0.0.jar:na]

Target: master
Require-book: no
Require-notes: no
Patch:
Acked-by: