scripts: make boot-loader more robust
An RPM file might not contain some files that was present in an RPM 
file from an earlier version contains; for example, if the version of 
some external dependency has changed or dCache class files have been 
repackaged into fewer jar files.

Sometimes, rpm will fail to remove these unneeded files; that is, 
after upgrading the version of dCache, files that are no longer needed 
are not removed.  I've yet to figure out precisely under what 
circumstances this happens, but I've noticed that, after upgrading to 
1.9.12 (or trunk), srm-tomcat.jar and xrootd-tokenauthz.jar sometimes 
remain in /opt/d-cache/classes directory.

The script /opt/d-cache/share/lib/bootLoader.sh is responsible for 
invoking the boot-loader.  To build the class-path for the Java 
invocation, the bootLoader.sh script uses the '*' short-hand.  This 
short-hand will include all jar files in a particular directory with 
an unspecified order.  If rpm failed to remove xrootd-tokenauthz.jar 
then that jar file will be included somewhere within the boot-loader 
class-path.

With dCache v1.9.5-24 (and likely with other versions of dCache), the 
xrootd-tokenauthz.jar file contains many of the class files in 
dcache.jar.  This looks like a bug in the build ant scripts.

The result of all this is that, if xrootd-tokenauthz.jar precedes 
dcache.jar in the auto-generated class-path then old (from 1.9.5) 
implementations of classes are used instead of the current ones, found 
in dcache.jar.  Using 1.9.5-era class files is sufficient to prevent 
the bootloader from running, so breaking all dCache shell commands.  
The following error message is returned:

[root@dcachetogo ~]# /opt/d-cache/bin/dcache status
Exception in thread "main" java.lang.NoSuchMethodError: diskCacheV111.util.FsPath.getName()Ljava/lang/String;
        at org.dcache.boot.Layout.load(Layout.java:85)
        at org.dcache.boot.BootLoader.loadLayout(BootLoader.java:123)
        at org.dcache.boot.BootLoader.main(BootLoader.java:163)

This patch fixes this problem by making the boot-loader more robust 
against alien jar files located in /opt/d-cache/classes directory.

Note that this patch fixes the problem with the 
"/opt/d-cache/classes/*" short-hand.  A similar problem exists for the 
two other short-hand notation in the classpath 
("/opt/d-cache/classes/lib/*" and "/opt/d-cache/classes/logback/*").  
These are not fixed with this patch as they would require 
version-specific jar filename.  A future patch may fix these problems 
by building bootLoader.sh from a template version during the build 
process, so injecting the correct jar filenames.

Target: trunk
Request: 1.9.12
Request: 1.9.11
Request: 1.9.10
Patch: http://rb.dcache.org/r/3174/
Acked-by: Gerd Behrmann