ftp: java.lang.IllegalStateException: Cannot send after the producer is closed.
Motivation:
10 Oct 2018 11:07:34 (FTP-srm-cosgrove-AAV33C7CoXg) [door:FTP-srm-cosgrove-AAV33C7CoXg@cosgroveDomain tarpool_002 DoorTransferFinished 00009D67503DECA14FEC9191A13467CC5BBC] Possible bug detected.
java.lang.IllegalStateException: Cannot send after the producer is closed.
    at org.apache.kafka.clients.producer.internals.RecordAccumulator.append(RecordAccumulator.java:198) ~[kafka-clients-1.0.0.jar:na]
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:806) ~[kafka-clients-1.0.0.jar:na]
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:760) ~[kafka-clients-1.0.0.jar:na]
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:648) ~[kafka-clients-1.0.0.jar:na]
    at org.dcache.ftp.door.AbstractFtpDoorV1$FtpTransfer.lambda$new$0(AbstractFtpDoorV1.java:1017) ~[dcache-ftp-4.2.12.jar:4.2.12]
    at org.dcache.util.Transfer.notifyBilling(Transfer.java:1217) ~[dcache-core-4.2.12.jar:4.2.12]
    at org.dcache.ftp.door.AbstractFtpDoorV1$FtpTransfer.onFinish(AbstractFtpDoorV1.java:1277) ~[dcache-ftp-4.2.12.jar:4.2.12]
    at org.dcache.util.AsynchronousRedirectedTransfer$Monitor.doFinish(AsynchronousRedirectedTransfer.java:178) [dcache-core-4.2.12.jar:4.2.12]
    at org.dcache.util.AsynchronousRedirectedTransfer$Monitor.finished(AsynchronousRedirectedTransfer.java:220) [dcache-core-4.2.12.jar:4.2.12]
    at org.dcache.util.AsynchronousRedirectedTransfer.lambda$finished$2(AsynchronousRedirectedTransfer.java:92) [dcache-core-4.2.12.jar:4.2.12]
    at org.dcache.util.CDCExecutorDecorator$WrappedRunnable.run(CDCExecutorDecorator.java:62) ~[dcache-core-4.2.12.jar:4.2.12]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_181]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_181]
    at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_181]
10 Oct 2018 11:07:34 (FTP-srm-cosgrove-AAV33C7CoXg) [door:FTP-srm-cosgrove-AAV33C7CoXg@cosgroveDomain tarpool_002 DoorTransferFinished 00009D67503DECA14FEC9191A13467CC5BBC] Transfer error: 451 Transient internal error

Target: master
Request: 4.2
Requires-notes: yes
Requires-book: no
Acked-by:  Paul