dcache-resilience: protect access of pool info map against NoSuchElementException
Motivation:

In designing the PoolInfoMap, we created a special class, the NonReindexableList,
in order to be able to remove elements from a list without reassigning stale
index numbers.  This was so that we could update the map and not have waiting
file operations reference unexpected pools, units or groups.

This map throws a NoSuchElementException if get finds a null at an (old) index,
or if an element is not in the list.  This was to avoid having to handle
nulls.  The idea was that if the list were being accessed this way, something
was wrong (a bug).

However, recently I have discovered that there is a (non-buggy) condition which
was unaccounted for, where it is possible that operations could try to reference
stale information.  This occurs _at the point of removal_.  That is, when the
pool monitor contains information suggesting the removal of a pool from the
psu, resilience triggers a cancel on any existing operations referencing those
pools.  The code paths from cancel is such that an attempt to retrieve
those old units, pools or groups is indeed made after the write lock on the
map is released.  Depending on where it happens, stack traces such as the
following may occur.  The uncaught exception kills the file operation map
thread.

```
03 Aug 2020 14:37:37 () [] Uncaught exception in thread FileOperationMap  -- handle stale information
java.util.NoSuchElementException: p-noble-stkendca12a-10
        at org.dcache.util.NonReindexableList.indexOf(NonReindexableList.java:192)
        at org.dcache.resilience.data.PoolInfoMap.getPoolIndex(PoolInfoMap.java:412)
        at org.dcache.resilience.data.FileFilter.matchesPool(FileFilter.java:98)
        at org.dcache.resilience.data.FileCancelFilter.matchesPool(FileCancelFilter.java:79)
        at org.dcache.resilience.data.FileFilter.matches(FileFilter.java:163)
```

In some cases, an NPE may also occur if a null value is actually given to
the map.

Motivation:

To be entirely safe, we wrap all access to the three NonReindexableLists
with "safe" accessors which either return a "Missing" string name or
an index which is understood to represent a missing (former) entry.

We have also adjusted several methods not to call other methods which
would unnecessarily cause the thread to re-enter the read lock (for
efficiency).

We have also added to JUnit tests to test that no exception is thrown.

Result:

More robust handling of PSU changes which remove pool, unit or group
mappings.

Target: master
Request: 6.2
Request: 6.1
Request: 6.0
Request: 5.2
Patch: https://rb.dcache.org/r/12507/
Requires-notes: yes
Requires-book: no
Acked-by: Tigran