core: make it optional whether builder creates a readOnly subject
Motivation:

NFS currently requires that the supplied Subject is not readOnly. A
recent patch changed this behaviour, resulting in operations failing
with a stack-trace:

    04 Nov 2016 06:02:43 (NFS-prometheus) [] Unhandled exception:
    java.lang.IllegalStateException: Subject is read-only
            at javax.security.auth.Subject$SecureSet.add(Subject.java:1103) ~[na:1.8.0_111]
            at java.util.Collections$SynchronizedCollection.add(Collections.java:2035) ~[na:1.8.0_111]
            at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.lambda$process$24(ProxyIoMdsOpFactory.java:52) ~[dcache-nfs-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
            at java.security.AccessController.doPrivileged(Native Method) ~[na:1.8.0_111]
            at javax.security.auth.Subject.doAs(Subject.java:360) ~[na:1.8.0_111]
            at org.dcache.chimera.nfsv41.door.proxy.ProxyIoMdsOpFactory$1.process(ProxyIoMdsOpFactory.java:50) ~[dcache-nfs-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
            at org.dcache.nfs.v4.NFSServerV41.NFSPROC4_COMPOUND_4(NFSServerV41.java:152) ~[nfs4j-core-0.13.0.jar:0.13.0]
            at org.dcache.nfs.v4.xdr.nfs4_prot_NFS4_PROGRAM_ServerStub.dispatchOncRpcCall(nfs4_prot_NFS4_PROGRAM_ServerStub.java:48) [nfs4j-core-0.13.0.jar:0.13.0]
            at org.dcache.xdr.RpcDispatcher$1.run(RpcDispatcher.java:109) [oncrpc4j-core-2.6.0.jar:na]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:591) [grizzly-framework-2.3.24.jar:2.3.24]
            at org.glassfish.grizzly.threadpool.AbstractThreadPool$Worker.run(AbstractThreadPool.java:571) [grizzly-framework-2.3.24.jar:2.3.24]
            at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]

Modification:

Make it configurable whether or not the Subject building creates a
readOnly Subject; by default it creates a Subject that may be further
modified.

Result:

An unreleased regression is fixed: NFS may be used again.

Target: master
Requires-notes: no
Requires-book: no
Patch: https://rb.dcache.org/r/9884
Acked-by: Tigran Mkrtchyan