srm-client: prevent unhelpful NullPointerException
Motivation:
When attempting to use a password protected X.509 certificate with the srm client, a NullPointerException is logged without any further information. This is a bug and does not help discover the underlying problem.

Modification:
The SRMClient attempts to get the credential by creating a new instance of PEMCredential, which expects a key password as a char array. Because it is assumed that the key is not password protected, a value of null is passed, leading to a NullPointerException later on.
This is changed to instead passing an empty char array, which will result in a more helpful error message.

Result:
A better error message is logged when attempting to use a password protected credential:
srm client error:
java.io.IOException: Error decrypting private key: the password is incorrect or the PEM data is corrupted.

Target: master
Requires-notes: no
Requires-book: no
Patch: https://rb.dcache.org/r/12667/
Acked-by: Tigran Mkrtchyan