Set /var/log/dcache to be owned by dcache:root instead of dcache:dcache
Fixes the below error with logrotate 3.8.6 on EL7.

<pre>
considering log /var/log/dcache/PoolDomain.log
error: skipping "/var/log/dcache/PoolDomain.log" because
parent directory has insecure permissions (It's world writable or
writable by group which is not "root") Set "su" directive in config file
to tell logrotate which user/group should be used for rotation.
</pre>

Signed-off-by: Johan Guldmyr <johan.guldmyr@csc.fi>