SRM : Fix IPV6 logging for SRM
Motivation:-

SRM module does not work with IPV6 in dcache 7.1.1 version
It throws error :-
java.lang.IllegalArgumentException: '[2001:1458:301:cd:0:0:100:44]' is
not an IP string literal.
at
com.google.common.net.InetAddresses.formatIllegalArgumentException(InetAddresses.java:989)
    at com.google.common.net.InetAddresses.forString(InetAddresses.java:140)
    at org.dcache.srm.util.Axis.getRemoteSocketAddress(Axis.java:93)
    at diskCacheV111.srm.SrmHandler$AccessLogger.response(SrmHandler.java:889)
    at diskCacheV111.srm.SrmHandler.handleRequest(SrmHandler.java:369)
    at diskCacheV111.srm.SrmHandlerAdapter.srmPing(SrmHandlerAdapter.java:367)

Modification:-
Change InetAddresses.forString to InetAddresses.forUriString in
1) dcache-srm/src/main/java/diskCacheV111/srm/SrmHandler.java - srmHandler function
2) srm-server/src/main/java/org/dcache/srm/util/Axis.java - InetSocketAddress function

Result:-
SRM module works with ipv6 address.

Target: master
Require-notes: yes
Require-book: no
Request: 7.1
Ticket: 10145
Patch: https://rb.dcache.org/r/13091/
Acked-by: lea