chimera: adding password.file to chimera
Motivation:
when moving from dcache.db.password to dcache.db.password.file
(pgpass), the dcache.conf is world readable. This had the
unfortunate side effect that the "chimera" shell command throws Exception:

ERROR - HikariPool-1 - Exception during pool initialization.
org.postgresql.util.PSQLException: FATAL: password authentication failed
for user "dcache"
org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:525)
org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:146)
org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:197)
org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
(PgConnection.java:211)
org.postgresql.Driver.connect(Driver.java:261)
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:117)
com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:123)
com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:375)
com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:204)
com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:459)
com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:533)
com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:114)
com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:72)
org.dcache.chimera.FsFactory.getDataSource(FsFactory.java:53)
org.dcache.chimera.FsFactory.createFileSystem(FsFactory.java:33)
org.dcache.chimera.cli.Shell.<init>(Shell.java:108)
org.dcache.chimera.cli.Shell.main(Shell.java:100)

Modification:

Modify Shell to use pgPass to access password file

Result:

No more stack traces. Shell interface works with password file.

Target: master
Request: 7.1
Request: 7.0
Ticket: 10130
Requires-notes: yes
Requires-book: no