pool: Suppress stack traces for non-fatal DCAP failures
There is no need to log these errors with a stack trace:

14 Jul 2011 05:54:36 (hpc2n_umu_se_026) [dcsc_ku_dk_047 PoolDeliverFile 0000C$
java.io.IOException: Broken pipe
at sun.nio.ch.FileDispatcher.write0(Native Method) ~[na:1.6.0_24]
at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:29) ~[na:1.6.0_24]
at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:72) ~[na:1.6.0_24]
at sun.nio.ch.IOUtil.write(IOUtil.java:43) ~[na:1.6.0_24]
at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:334) ~[na:1.6.0_$
at org.dcache.pool.movers.DCapProtocol_3_nio.doTheRead(DCapProtocol_3_nio.jav$
at org.dcache.pool.movers.DCapProtocol_3_nio.runIO(DCapProtocol_3_nio.java:53$
at org.dcache.pool.classic.PoolIOReadTransfer.transfer(PoolIOReadTransfer.jav$
at org.dcache.pool.classic.LegacyMoverExecutorService$2.run(LegacyMoverExecut$
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) [n$
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6$
at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_24]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.$
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java$
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_24]


Target: trunk
Request: 1.9.13
Request: 1.9.12
Acked-by: Jan Schaefer <jan.schaefer@desy.de>
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: http://rb.dcache.org/r/3593/
Committed: trunk@16038 
Merge-request: http://rt.dcache.org/Ticket/Display.html?id=6471
Signed-off-by: Gerd Behrmann