pom: use nfs4j-0.17.10
Zero code change bugfix - compiled with java8 to avoid

java.lang.NoSuchMethodError: java.nio.ByteBuffer.limit(I)Ljava/nio/ByteBuffer

as java9 have introduced ByteBuffer#limit, which is used instead of
Buffer#limit when compiled with java9+.

Acked-by: Jürgen Starek
Target: master, 5.0, 4.2
Require-book: no
Require-notes: yes