srm: Reimplement legacy close
Motivation:

Old SRM clients (including all those released by dcache.org) do not
handle the TLS close handshake protocol gracefully.

A recent upgrade of Jetty has caused our workaround for this problem
to spam the log files.

Modification:

Rather than throwing a runtime exception in the GSI engine, we now
obay the contract of SSLEngine and properly suppress the close handshake
messages.

Result:

No more:

java.lang.RuntimeException: Deliberately force the connection to close to workaround client bugs.

nor

Unexpected thread death: org.eclipse.jetty.util.thread.QueuedThreadPool$3@66ae829c in jetty-srm{STARTED,10<=10<=500,i=4,q=0}

Target: trunk
Require-notes: no
Require-book: no
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: https://rb.dcache.org/r/8714/