dcache-qos,system-test:  override db property to hsqldb
Motivation:

During system tests:

```
Unexpected error running Liquibase: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname
and port are correct and that the postmaster is accepting TCP/IP connections.
ERROR - org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that
the postmaster is accepting TCP/IP connections.
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: org.postgresql.util.PSQLException: Connection to
localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:69)
	at liquibase.integration.commandline.Main.doMigration(Main.java:884)
	at liquibase.integration.commandline.Main.run(Main.java:175)
	at liquibase.integration.commandline.Main.main(Main.java:94)
```

Neglected to override the new db properties for `qos-engine`.

Modification:

Added the override to the hsqlsdb properties.

Result:

No more stack trace/connection failure to postgresqls (?).

Target: master
Patch: https://rb.dcache.org/r/14099/
Requires-notes: no (unreleased)
Acked-by: Svenja