namespace: ensure that access latency and retention policy are always defined
Motivation:
Many parts in dcache expected that files access latency and retention
policy are always defined. The namespace fallbacks to default values, if
there are no explicit tags are defined. However, there is shortcat tha
skips default values if WriteToken tag is specified. The lately
introduces Archivemetadata is a functionality that directry affected by
this behaviour:

```
java.lang.IllegalStateException: Attribute is not defined: RETENTION_POLICY
	at org.dcache.vehicles.FileAttributes.guard(FileAttributes.java:335)
	at org.dcache.vehicles.FileAttributes.getRetentionPolicy(FileAttributes.java:504)
	at org.dcache.webdav.DcacheResourceFactory$WriteTransfer.createNameSpaceEntry(DcacheResourceFactory.java:1940)
	at org.dcache.webdav.DcacheResourceFactory.createFile(DcacheResourceFactory.java:752)
	at org.dcache.webdav.DcacheDirectoryResource.createNew(DcacheDirectoryResource.java:148)
	at io.milton.http.http11.PutHandler.processCreate(PutHandler.java:229)
	at io.milton.http.http11.PutHandler.process(PutHandler.java:207)
	at org.dcache.webdav.DcacheStandardFilter.process(DcacheStandardFilter.java:50)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at org.dcache.webdav.transfer.CopyFilter.process(CopyFilter.java:278)
	at io.milton.http.FilterChain.process(FilterChain.java:46)
	at io.milton.http.HttpManager.process(HttpManager.java:158)
	at org.dcache.webdav.MiltonHandler.handle(MiltonHandler.java:77)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:59)
```

Modification:
Remove dependency on WriteToken. Update Spacemanager (which expected no
access latency and retention policy) to override the value, if space
token has a different value. The mismatch is logged.

Result:
The access latency and retention policies are always defined.

Fixes: #8033
Acked-by: Dmitry Litvintsev
Target: master, 11.2
Require-book: no
Require-notes: yes