Httpd IllegalStateException when authenticated=true but keystone or truststore path does not exist
The server shutdown logic was incorrect, in that under certain failure conditions the code was trying to destroy it when its state was not yet running.

Patch fixes the state machine problem so that cleanup uniformly calls stop before destroy.

Eliminated the ad hoc check for the truststore and keystore  paths.  This now fails fast as any other error will.  E.g.,

24 Aug 2012 09:37:47 (httpd) [] FAILED org.eclipse.jetty.http.ssl.SslContextFactory@30c4f4d8#FAILED: java.io.FileNotFoundException: /etc/dcache/certificates.jks (No such file or directory)
java.io.FileNotFoundException: /etc/dcache/certificates.jks (No such file or directory)
	at java.io.FileInputStream.open(Native Method) ~[na:1.7.0]
	at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.7.0]
	at org.eclipse.jetty.util.resource.FileResource.getInputStream(FileResource.java:276) ~[jetty-util-7.5.4.v20111024.jar:7.5.4.v20111024]
	at org.eclipse.jetty.util.security.CertificateUtils.getKeyStore(CertificateUtils.java:41) ~[jetty-util-7.5.4.v20111024.jar:7.5.4.v20111024]
	at org.eclipse.jetty.http.ssl.SslContextFactory.getKeyStore(SslContextFactory.java:1056) ~[jetty-http-7.5.4.v20111024.jar:7.5.4.v20111024]
	at org.eclipse.jetty.http.ssl.SslContextFactory.loadTrustStore(SslContextFactory.java:1030) ~[jetty-http-7.5.4.v20111024.jar:7.5.4.v20111024]
	at org.eclipse.jetty.http.ssl.SslContextFactory.doStart(SslContextFactory.java:268) ~[jetty-http-7.5.4.v20111024.jar:7.5.4.v20111024]
...

24 Aug 2012 09:37:47 (httpd) [] server failure, calling cleanUp ...
(666) file:/usr/share/dcache/services/httpd.batch: line 232: (3) java.util.concurrent.ExecutionException: java.io.FileNotFoundException: /etc/dcache/certificates.jks (No such file or directory) from ac_create_$_2_3

Target:  trunk
Patch: http://rb.dcache.org/r/4836
Bug:   http://rt.dcache.org/Ticket/Display.html?id=7354
Request: 2.4
Acked-by: Dmitry

Require-notes:  Yes
Require-book: No