libs: use jline2-2.14.6 with small bugfix
Motivation:
depending on TERM env variable the jline can fail to pars the hex
numbers:

[ERROR] Failed to construct terminal; falling back to unsupported
java.lang.NumberFormatException: For input string: "0x100"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.valueOf(Integer.java:983)
	at jline.internal.InfoCmp.parseInfoCmp(InfoCmp.java:59)
	at jline.UnixTerminal.parseInfoCmp(UnixTerminal.java:242)
	at jline.UnixTerminal.<init>(UnixTerminal.java:65)
	at jline.UnixTerminal.<init>(UnixTerminal.java:50)

The issue is fixed in jline-2.14.4

Modification:
Update jline to latest version with various minor bugfixes

Result:
No stack trace when parsing hex numbers.

Fixes: #6411
Acked-by: Lea Morschel
Target: master
Require-book: no
Require-notes: yes