systemtest: fix populate script for when systemtest already exists
Motivation:

Running maven without the 'clean' target results in the populate script
being run on an existing system-test deployment.  This, in turn, results
in the following error:

    ln: failed to create symbolic link ‘/home/paul/git/dCache/packages/system-test/target/dcache/share/lib/services.sh’: File exists
    [ERROR] Command execution failed.
    org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
            at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
            at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
            at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
            at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
    [...]

Modification:

Remove any existing services.sh file before creating the symbolic link.

Result:

Able to build system-test without 'clean' target.

Target: master
Require-notes: no
Require-book: no
Patch: https://rb.dcache.org/r/10383/
Acked-by: Tigran Mkrtchyan