Add try block to BootLoader to report command execution exceptions through logging system
The reason for this change is to enable reporting of these fatal exceptions as alarms (such as the inability to execute
ac_create in the following case -- where the database connections have maxed out):

(666) file:/usr/share/dcache/services/billing.batch: line 63: (3)
java.lang.RuntimeException: dmg.util.CommandThrowableException: (3)
Failed to create bean 'jdbc-billing-info-access' : FATAL: remaining
connection slots are reserved for non-replication superuser connections
from ac_create_$_2_3 

Obviously this message needs to go through the logging system for it to become an alarm.

The final agreed-upon solution is simply to log all exceptions that are caught if the command is "start", without any additional try-catch blocks.

Testing: Redeployed dCache, started and observed logging of alarm associated with example above.

Target: trunk
Patch: http://rb.dcache.org/r/5137
Acked-by: Paul
Require-book: no
Require-notes: yes
Request: 2.5

Release notes:  System start-up exceptions for a given domain can now be caught and processed as alarms.