billing: fix stacktrace and slow shutdown if in refresh
Motivation:

If dCache starts shutting down when billing is in refresh then the
following stacktrace is logged:

    java.lang.RuntimeException: Unexpected error: this is probably a bug. Please report to the dCache team.
            at org.dcache.webadmin.controller.impl.StandardBillingService.load(StandardBillingService.java:219) ~[classes/:na]
            at org.dcache.webadmin.controller.impl.StandardBillingService.generatePlot(StandardBillingService.java:420) ~[classes/:na]
            at org.dcache.webadmin.controller.impl.StandardBillingService.refresh(StandardBillingService.java:348) ~[classes/:na]
            at org.dcache.webadmin.controller.impl.StandardBillingService.run(StandardBillingService.java:360) ~[classes/:na]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
    Caused by: java.lang.InterruptedException: null
            at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:431) ~[guava-19.0.jar:na]
            at org.dcache.cells.CellStub.get(CellStub.java:591) ~[dcache-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
            at org.dcache.cells.CellStub.sendAndWait(CellStub.java:289) ~[dcache-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
            at org.dcache.services.billing.histograms.data.TimeFrameHistogramDataProxy.invoke(TimeFrameHistogramDataProxy.java:94) ~[dcache-core-3.0.0-SNAPSHOT.jar:3.0.0-SNAPSHOT]
            at com.sun.proxy.$Proxy42.getDcBytesHistogram(Unknown Source) ~[na:na]
            at org.dcache.webadmin.controller.impl.StandardBillingService.load(StandardBillingService.java:163) ~[classes/:na]
            ... 4 common frames omitted

The interrupt is also not propagated, resulting in a delayed shutdown.

Modification:

Allow InterruptedException to propagate

Result:

No more stacktrace; timely shutdown of dcache.

Target: master
Request: 3.0
Request: 2.16
Request: 2.15
Request: 2.14
Request: 2.13
Patch: https://rb.dcache.org/r/9846/
Acked-by: Albert Rossi