common-security: Do not log stack traces for CANL notifications
Motivation:

CANL will notify a listener of any problems loading trust material. These are
not bugs and should not cause a stack trace to be logged.

Modification:

Do not log a stack trace on CANL notifications. Only the exception message
is logged.

Result:

Avoid these errors in the log:

03 Nov 2015 07:35:52 (SRM-bunsen) [] Problem loading OCSP from http://ocsp.cern.ch/ocsp:
org.bouncycastle.ocsp.OCSPException: Response has expired on: Tue Nov 03 06:35:24 CET 2015
        at eu.emi.security.authn.x509.helpers.ocsp.OCSPClientImpl.verifyTimeRange(OCSPClientImpl.java:387) ~[canl-1.3.3.jar:1.3.3]
        at eu.emi.security.authn.x509.helpers.ocsp.OCSPClientImpl.verifyResponse(OCSPClientImpl.java:363) ~[canl-1.3.3.jar:1.3.3]
        at eu.emi.security.authn.x509.helpers.ocsp.OCSPCachingClient.queryForCertificate(OCSPCachingClient.java:108) ~[canl-1.3.3.jar:1.3.3]
        at eu.emi.security.authn.x509.helpers.ocsp.OCSPCachingClient.queryForCertificate(OCSPCachingClient.java:61) ~[canl-1.3.3.jar:1.3.3]
        at eu.emi.security.authn.x509.helpers.ocsp.OCSPVerifier.verify(OCSPVerifier.java:95) ~[canl-1.3.3.jar:1.3.3]

Target: trunk
Request: 2.14
Require-notes: no
Require-book: no
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: https://rb.dcache.org/r/8735/