doors: Fix IllegalStateException in Transfer class
The problem was recently introduced on trunk. When the target file
exists the following fails:

behrmann@behrmann-laptop:~/dCache/trunk$ /opt/globus-vdt-1.2.3/bin/globus-url-copy -nogridftp2 gsiftp://dcache-vm//test-1297766764-9 gsiftp://dcache-vm//test-1297766765-1
error: the server sent an error response: 500 500 Operation failed due to internal error: Attribute is not defined: STORAGEINFO


Target: trunk
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: http://rb.dcache.org/r/3062/