srm: fix stacktrace on database failure
Motivation:

A log file indicated a stacktrace like

    20 Oct 2017 10:56:25 (SrmManager) [DoM:20480104:srm2:ls:1530164743:1530164744 DoM:20480104:srm2:ls SRM-srm] Uncaught exception in thread pool-11-thread-28281
    org.springframework.transaction.CannotCreateTransactionException: Could not open JDBC Connection for transaction; nested exception is java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
            at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:245) ~[spring-jdbc-4.2.6.RELEASE.jar:4.2.6.RELEASE]
            at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373) ~[spring-tx-4.2.6.RELEASE.jar:4.2.6.RELEASE]
            at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:130) ~[spring-tx-4.2.6.RELEASE.jar:4.2.6.RELEASE]
            at org.dcache.srm.request.sql.DatabaseJobStorage.saveJob(DatabaseJobStorage.java:242) ~[srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.AsynchronousSaveJobStorage$1.run(AsynchronousSaveJobStorage.java:91) ~[srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.AsynchronousSaveJobStorage.saveJob(AsynchronousSaveJobStorage.java:110) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.ForceOnlyJobStorageDecorator.saveJob(ForceOnlyJobStorageDecorator.java:51) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.SharedMemoryCacheJobStorage.saveJob(SharedMemoryCacheJobStorage.java:98) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.CanonicalizingJobStorage.saveJob(CanonicalizingJobStorage.java:106) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.request.Job.saveJob(Job.java:215) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.request.Job.setState(Job.java:300) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.request.LsFileRequest.fail(LsFileRequest.java:228) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.request.LsFileRequest.run(LsFileRequest.java:209) [srm-server-2.16.42.jar:2.16.42]
            at org.dcache.srm.scheduler.Scheduler$JobWrapper.run(Scheduler.java:401) [srm-server-2.16.42.jar:2.16.42]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
            at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
    Caused by: java.sql.SQLException: HikariPool-1 - Interrupted during connection acquisition
            at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:182) ~[HikariCP-2.4.6.jar:na]
            at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:147) ~[HikariCP-2.4.6.jar:na]
            at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:83) ~[HikariCP-2.4.6.jar:na]
            at org.dcache.db.AlarmEnabledDataSource.getConnection(AlarmEnabledDataSource.java:151) ~[dcache-common-2.16.42.jar:2.16.42]
            at org.springframework.jdbc.datasource.DataSourceTransactionManager.doBegin(DataSourceTransactionManager.java:204) ~[spring-jdbc-4.2.6.RELEASE.jar:4.2.6.RELEASE]
            ... 16 common frames omitted
    Caused by: java.lang.InterruptedException: null
            at java.util.concurrent.locks.AbstractQueuedLongSynchronizer.doAcquireSharedNanos(AbstractQueuedLongSynchronizer.java:817) ~[na:1.8.0_131]
            at java.util.concurrent.locks.AbstractQueuedLongSynchronizer.tryAcquireSharedNanos(AbstractQueuedLongSynchronizer.java:1106) ~[na:1.8.0_131]
            at com.zaxxer.hikari.util.QueuedSequenceSynchronizer.waitUntilSequenceExceeded(QueuedSequenceSynchronizer.java:92) ~[HikariCP-2.4.6.jar:na]
            at com.zaxxer.hikari.util.ConcurrentBag.borrow(ConcurrentBag.java:169) ~[HikariCP-2.4.6.jar:na]
            at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:165) ~[HikariCP-2.4.6.jar:na]
            ... 20 common frames omitted

Modification:

The problem comes about from commit b77d5328, which changed the save to
happen within a transaction.  This changed the nature of the exceptions
being thrown.

This patch updates the throws annotation and catch statements to match
the newer Exception type.

Result:

No more stack-trace when SRM fails to write to the database.

Target: master
Request: 3.2
Request: 3.1
Request: 3.0
Request: 2.16
Require-notes: yes
Require-book: no
Ticket: http://rt.dcache.org/Ticket/Display.html?id=9284
Issue: https://github.com/dCache/dcache/issues/3613
Patch: https://rb.dcache.org/r/10569/
Closes: #3613
Acked-by: Tigran Mkrtchyan