transfermanagers: Fix database settings
We recently made changes to the configuration of transfermanagers
to make its database show up in 'dcache database ls'. This change
introduced a regression by setting the database name to null
in case srmDbLogEnabled was set to false. This was done believing
that transfermanagers would not use a database when that property
was set to false. This assumption is invalid as transfermanagers
in fact always accesses the SRM database. Thus when srmDbLogEnabled
is set to false, we currently get the following error:

org.postgresql.util.PSQLException: FATAL: database "srmdcache" does not exist
        at org.postgresql.core.v3.ConnectionFactoryImpl.readStartupMessages(ConnectionFactoryImpl.java:469)
        at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:112)
        at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:66)
        at org.postgresql.jdbc2.AbstractJdbc2Connection.<init>(AbstractJdbc2Connection.java:125)
        at org.postgresql.jdbc3.AbstractJdbc3Connection.<init>(AbstractJdbc3Connection.java:30)
        at org.postgresql.jdbc3g.AbstractJdbc3gConnection.<init>(AbstractJdbc3gConnection.java:22)
        at org.postgresql.jdbc4.AbstractJdbc4Connection.<init>(AbstractJdbc4Connection.java:30)
        at org.postgresql.jdbc4.Jdbc4Connection.<init>(Jdbc4Connection.java:24)
        at org.postgresql.Driver.makeConnection(Driver.java:393)
        at org.postgresql.Driver.connect(Driver.java:267)
        at java.sql.DriverManager.getConnection(DriverManager.java:579)
        at java.sql.DriverManager.getConnection(DriverManager.java:221)
        at org.dcache.srm.request.sql.JdbcConnectionPool.getConnection(JdbcConnectionPool.java:134)
        at org.dcache.srm.request.sql.RequestsPropertyStorage.dbInit(RequestsPropertyStorage.java:147)
        at org.dcache.srm.request.sql.RequestsPropertyStorage.<init>(RequestsPropertyStorage.java:118)
        at org.dcache.srm.request.sql.RequestsPropertyStorage.initPropertyStorage(RequestsPropertyStorage.java:405)
        at diskCacheV111.services.TransferManager.init(TransferManager.java:126)
        at org.dcache.cells.AbstractCell.executeInit(AbstractCell.java:339)
        at org.dcache.cells.AbstractCell$1.call(AbstractCell.java:296)
        at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:334)
        at java.util.concurrent.FutureTask.run(FutureTask.java:166)
        at dmg.cells.nucleus.CellNucleus$1.run(CellNucleus.java:658)
        at java.lang.Thread.run(Thread.java:722)

This patch fixes this regression.

Target: trunk
Request: 2.3
Request: 2.2
Require-book: no
Require-notes: yes
Ticket: http://rt.dcache.org/Ticket/Display.html?id=7306
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: http://rb.dcache.org/r/4814/