gplazma: Suppress log4j initialization in XACML plugin
The XACML plugin fails with:

Uncaught exception in thread pool-2-thread-2
java.lang.NoClassDefFoundError: org/apache/log4j/Layout
at org.glite.security.trustmanager.ContextWrapper.loadConfig(ContextWrapper.java:344)~[trustmanager-3.0.3-1.jar:na]
at org.glite.security.trustmanager.ContextWrapper.<init>(ContextWrapper.java:274)~[trustmanager-3.0.3-1.jar:na]

This is because the EMI trustmanager tries to initialize log4j. Since we
don't package log4j this initialization fails.

The initialization can be suppressed by defining the wantLog4jSetup
system property.

Target: trunk
Request: 2.1
Request: 2.0
Request: 1.9.12
Ticket: http://rt.dcache.org/Ticket/Display.html?id=6894
Acked-by: Jan Schaefer <jan.schaefer@desy.de>
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: http://rb.dcache.org/r/4143/