srm-server: add servlet webapp-2.3.dtd file
The SRM server makes use of an XML file that follows the Sevlet 2.3
deployment descriptor.  When receiving the first SRM operation, Jetty
will parse the deployment descriptor, which requires the corresponding
DTD.

Previously (with Jetty 8) the DTD came as part of the servlet-api-2.x
jar file.  Jetty 9 depends on servlet-api 3.1, which does not contain
the deployment descriptor DTD:

    https://java.net/jira/browse/SERVLET_SPEC-115

Therefore, when it receives the first SRM operation, dCache will
download the DTD from java.sun.com.  For most sites, this is merely
undesirable, but if the dCache instance is not connected to the
Internet then this is problematic as a stack-trace is logged with the
root cause of:

    java.net.UnknownHostException: java.sun.com

and the SRM does not work.

This patch works around the problem by embedding the DTD in the
srm-server jar file.

Target: master
Patch: https://rb.dcache.org/r/7459
Acked-by: Gerd Behrmann
Request: 2.11
Require-notes: no
Require-book: no