chimera: fix writing into file level
Motivation:

14 May 2016 00:43:11 (PnfsManager) [dcache-photon17-08 PnfsFlag 0000A46614130D18483ABAF9FA374DD59B07] Exception in setFileAttributes: {}
org.dcache.chimera.IOHimeraFsException: PreparedStatementCallback; bad SQL grammar [UPDATE t_level_2 SET ifiledata=?,isize=? WHERE ino=?]; nested excepti
on is org.postgresql.util.PSQLException: ERROR: column "ino" does not exist
Position: 50
at org.dcache.chimera.JdbcFs.inTransaction(JdbcFs.java:210) ~[chimera-2.15.5.jar:2.15.5]
at org.dcache.chimera.JdbcFs.write(JdbcFs.java:1012) ~[chimera-2.15.5.jar:2.15.5]
at sun.reflect.GeneratedMethodAccessor290.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_92]
at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_92]
at org.dcache.commons.stats.MonitoringProxy.invoke(MonitoringProxy.java:54) ~[dcache-common-2.15.5.jar:2.15.5]
....

Modification:
fix sql statement to use correct field. Added unit test

Result:
exception is gone.

Fixes: #2407
Acked-by: Albert Rossi
Target: master, 2.15
Require-book: no
Require-notes: no