Revert "cells: Message payload serialization using FST"
This reverts commit f0804a64d5fc3c7ea4f529efb7c536ef5da1fe0b.

There was a compilation error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/paul/git/dCache/modules/dcache/src/test/java/org/dcache/boot/DomainConfigurationTest.java:[3,25] dmg.cells.nucleus.MsgSerializerJos is not public in dmg.cells.nucleus; cannot be accessed from outside package
```