gplazma: Make GlobusPrincipal compatibly with JGlobus
Motivation:

In anticipation of removing JGlobus we copied the GlobusPrincipal to the dCache
code. It was subsequently extended with an additional contructor. Later we
reintroduced JGlobus, causing there to be two versions of this class on the
classpath - one with the extra constructor and one without. Depending on load
order, the x509 plugin could fail with a NoSuchMethodError.

Modification:

Inline the constructor. The class is still duplicated in anticipation of
removing JGlobus.

Result:

Fixes http://rt.dcache.org/Ticket/Display.html?id=8859

Ticket: http://rt.dcache.org/Ticket/Display.html?id=8859
Require-notes: yes
Require-book: no
Target: trunk
Request: 2.14
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: https://rb.dcache.org/r/8863/
(cherry picked from commit 7ec11fde269034374d59f76c13499a3b0a2f5b06)