billing: Fix NoClassDefFoundError when invoking dcache billing command
Motivation:

$ dcache billing 0000099A014C0DE146C49BBDC3467BDD51C0
ERROR - Uncaught exception java.lang.NoClassDefFoundError: org/apache/curator/RetryPolicy

Modification:

Add curator-client to list of jar files.

Result:

No NoClassDefFoundError.

Target: trunk
Request: 2.16
Require-notes: no
Require-book: no
Fixes: #2482
Acked-by: Paul Millar <paul.millar@desy.de>

Reviewed at https://rb.dcache.org/r/9354/