pool: include the original IOException info DiskErrorCacheException
Motivation:
when back-end storage system throws IOException pool will fail to load
it's inventory and report DiskErrorCacheException. But it does not includes
the original IOException, which hides where problem is popped up.

Modification:
add original IOException into DiskErrorCacheException

Result:
better error tracing, e.g:

29 Jul 2016 12:12:29 (dcache-lab003-A) [] Fault occurred in repository: Internal repository error. Pool restart required:
diskCacheV111.util.DiskErrorCacheException: I/O error in healer: Failed to read from image 00003166298DEA814958A1D7C9E3C9DA10B8 : EINVAL(22), sys: ENOENT(2)
	at org.dcache.pool.repository.ConsistentReplicaStore.get(ConsistentReplicaStore.java:156) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache$Monitor.get(ReplicaStoreCache.java:113) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache$Monitor.access$700(ReplicaStoreCache.java:95) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache.get(ReplicaStoreCache.java:419) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.v5.ReplicaRepository.readReplicaRecord(ReplicaRepository.java:971) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.v5.ReplicaRepository.load(ReplicaRepository.java:502) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.classic.PoolV4$1.run(PoolV4.java:455) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]

vs

29 Jul 2016 12:20:58 (dcache-lab003-A) [] Fault occurred in repository: Internal repository error. Pool restart required:
diskCacheV111.util.DiskErrorCacheException: I/O error in healer: Failed to read from image 00003166298DEA814958A1D7C9E3C9DA10B8 : EINVAL(22), sys: ENOENT(2)
	at org.dcache.pool.repository.ConsistentReplicaStore.get(ConsistentReplicaStore.java:156) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache$Monitor.get(ReplicaStoreCache.java:113) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache$Monitor.access$700(ReplicaStoreCache.java:95) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ReplicaStoreCache.get(ReplicaStoreCache.java:419) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.v5.ReplicaRepository.readReplicaRecord(ReplicaRepository.java:971) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.v5.ReplicaRepository.load(ReplicaRepository.java:502) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.classic.PoolV4$1.run(PoolV4.java:455) [dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
Caused by: org.dcache.rados4j.RadosException: Failed to read from image 00003166298DEA814958A1D7C9E3C9DA10B8 : EINVAL(22), sys: ENOENT(2)
	at org.dcache.rados4j.Error.checkError(Error.java:16) ~[rados4j-0.0.1-SNAPSHOT.jar:na]
	at org.dcache.rados4j.RbdImage.read(RbdImage.java:35) ~[rados4j-0.0.1-SNAPSHOT.jar:na]
	at org.dcache.pool.repository.ceph.CephRepositoryChannel.read(CephRepositoryChannel.java:84) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at diskCacheV111.util.GenericIdChecksumFactory.computeChecksum(ChecksumFactory.java:211) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.classic.ChecksumModuleV1.verifyChecksum(ChecksumModuleV1.java:443) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.classic.ChecksumModuleV1.verifyChecksum(ChecksumModuleV1.java:428) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ConsistentReplicaStore.rebuildEntry(ConsistentReplicaStore.java:234) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	at org.dcache.pool.repository.ConsistentReplicaStore.get(ConsistentReplicaStore.java:154) ~[dcache-core-2.17.0-SNAPSHOT.jar:2.17.0-SNAPSHOT]
	... 6 common frames omitted

Acked-by: Paul MIllar
Acket-by: Olufemi Adeyemi
Target: master
Require-book: no
Require-notes: no