webdav: fail COPY early if file is currently being uploaded
Motivation:

Sites have reported errors like:

    java.lang.IllegalArgumentException: Required attributes are missing.
            at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135) ~[guava-24.1-jre.jar:na]
            at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:78) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:63) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at diskCacheV111.services.TransferManagerHandler.selectPool(TransferManagerHandler.java:421) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at diskCacheV111.services.TransferManagerHandler.storageInfoArrived(TransferManagerHandler.java:415) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at diskCacheV111.services.TransferManagerHandler.success(TransferManagerHandler.java:250) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at org.dcache.cells.AbstractMessageCallback.success(AbstractMessageCallback.java:32) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at org.dcache.cells.CellStub.lambda$addCallback$0(CellStub.java:516) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149) ~[dcache-core-5.1.0-SNAPSHOT.jar:5.1.0-SNAPSHOT]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_191]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_191]
            at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_191]

These are (likely) due to a client attempting to issue COPY request for
a file that is still being uploaded.

Modification:

Return a clear error (409 status code) to client if this happens.

Result:

Attempts by a client to copy a file that has not fully been uploaded now
results in a clear error response.

Target: master
Requires-notes: yes
Requires-book: no
Request: 5.0
Request: 4.2
Request: 4.1
Request: 4.0
Request: 3.2
Patch: https://rb.dcache.org/r/11545/
Acked-by: Dmitry Litvintsev