Chimera: Fix timing bug in Chimera test
I regularly observe this unit test failure:

Running org.dcache.chimera.BasicTest
Tests run: 58, Failures: 1, Errors: 0, Skipped: 4, Time elapsed: 15.447 sec <<< FAILURE!
testCreateFile(org.dcache.chimera.BasicTest)  Time elapsed: 0.187 sec  <<< FAILURE!
java.lang.AssertionError: crete file have to update parent's mtime
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.dcache.chimera.BasicTest.testCreateFile(BasicTest.java:70)


Results :

Failed tests:
  BasicTest.testCreateFile:70 crete file have to update parent's mtime



The problem is that the test relies on the file being created more than 1 ms
after the parent directory. Otherwise the test may not observe the mtime of
the parent being updated as the granularity of mtime is in milliseconds.

The patch solves the problem by introducing a 1 ms delay.

Target: trunk
Require-notes: no
Require-book: no
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: http://rb.dcache.org/r/5326/