rpm: remove weird "axis" command in scriptlet
Patch: http://rb.dcache.org/r/1805/ (committed as r.13944) removed the support in 
dCache for tomcat.  This involved altering the RPM spec file since we were no longer 
packaging tomcat-related files.

In addition to removing files we no longer wish to distribute, the patch also included 
"axis" as an extra command in the RPM spec file's preun scriptlet.

I've no idea what "axis" is (others I've spoken to are equally baffled) and 
uninstalling dCache fails with an error message:

[root@bumblebee ~]# rpm -e dcache-server /var/tmp/rpm-tmp.94681: line 11: axis: command not found
error: %preun(dcache-server-1.9.9-1rc.noarch) scriptlet failed, exit status 127

I suspect this was introduced by mistake.

This patch removes "axis" from the dcache-server spec file.  It also removes some 
commented-out spec-file headers as they may be misleading.

Patch: http://rb.dcache.org/r/2011/
Target: trunk
Recommend: 1.9.9
Acked-by: Timur
Acked-by: Tigran