cells: fix error reporting on tunnel disconnect
Motivation:
is a tunnel between two domain fails with an IOException without
error message, then alarm logic silently fails as:

 java.lang.IllegalArgumentException: A marker name cannot be null
 at org.slf4j.helpers.BasicMarker.<init>(BasicMarker.java:47)
 at org.slf4j.helpers.BasicMarkerFactory.getDetachedMarker(BasicMarkerFactory.java:96)
 at org.dcache.alarms.AlarmMarkerFactory.getMarker(AlarmMarkerFactory.java:102)
 at java.base/java.lang.Thread.run(Thread.java:833)
 at dmg.cells.network.LocationManagerConnector.run(LocationManagerConnector.java:121)
 at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$2(CellNucleus.java:725)

Modification:
Make sure that alarm gets meaning full error message, even if original
exceptions returns null on getMessage.

Result:
tunnel successfully reconnects on network errors.

Related-issue: #7519
Acked-by: Paul Millar
Target: master, 9.2
Require-book: no
Require-notes: yes