pool: bug-fixfor commit@74880c32a97...
Motivation

  master@74880c32a97.. 	commit  have broken  master with compilation ERROR:
 /scratch/jenkins/jenkins/workspace/dCache-master/modules/dcache/src/main/java/org/dcache/notification/BillingMessageSerializer.java:[3,19] package javafx.util does not exist

Modification

 wrong import is deleted.

 Target: master
 Require-book: no
 Require-notes: no
 Acked-by: Paul Millar ( by hand)