srm-server: make powermock test java11 compatible
[ERROR] org.dcache.srm.scheduler.SchedulerContainerTests.shouldScheduleCopyRequest  Time elapsed: 1.392 s  <<< ERROR!
java.lang.IllegalAccessError: class javax.xml.parsers.FactoryFinder (in unnamed module @0x3db6dd52) cannot access class jdk.xml.internal.SecuritySupport (in module java.xml) because module java.xml does not export jdk.xml.internal to unnamed module @0x3db6dd52
        at org.dcache.srm.scheduler.SchedulerContainerTests.mockScheduler(SchedulerContainerTests.java:53)
        at org.dcache.srm.scheduler.SchedulerContainerTests.setup(SchedulerContainerTests.java:77)

Acked-by:
Target: master
Require-book: no
Require-notes: no