srm, webdav: Fix connection shutdown in JettyGSIConnector
https://github.com/eclipse/jetty.project/commit/a6483bfa6f69bd3e0ffebd12ceabfc6cf4d3b967#diff-11
in Jetty changed how connections are closed. That change was made in
Jetty 7.3 to resolve https://bugs.eclipse.org/bugs/show_bug.cgi?id=340265

Since we didn't make the same change in JettyGSIConnector, dCache SRM
and webdav can get in a loop in which the following error is generated
over and over:

13 Jul 2011 10:39:27 (SRM-gonzo) [] EXCEPTION
java.net.SocketException: Connection reset
        at java.net.SocketInputStream.read(SocketInputStream.java:113) ~[na:1.6.0_24]
        at org.globus.gsi.gssapi.SSLUtil.read(SSLUtil.java:42) ~[cog-jglobus-dcache-1.8.0.jar:na]
        at org.globus.gsi.gssapi.net.impl.GSIGssInputStream.readToken(GSIGssInputStream.java:69) ~[cog-jglobus-dcache-1.8.0.jar:na]
        at org.globus.gsi.gssapi.net.impl.GSIGssInputStream.readMsg(GSIGssInputStream.java:44) ~[cog-jglobus-dcache-1.8.0.jar:na]
        at org.globus.gsi.gssapi.net.GssInputStream.hasData(GssInputStream.java:86) ~[cog-jglobus-dcache-1.8.0.jar:na]
        at org.globus.gsi.gssapi.net.GssInputStream.read(GssInputStream.java:60) ~[cog-jglobus-dcache-1.8.0.jar:na]
        at org.dcache.util.JettyGSIConnector$GsiSocket$GsiInputStream.read(JettyGSIConnector.java:665) ~[dcache.jar:na]
        at org.eclipse.jetty.io.ByteArrayBuffer.readFrom(ByteArrayBuffer.java:388) ~[jetty-io-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.eclipse.jetty.io.bio.StreamEndPoint.fill(StreamEndPoint.java:132) ~[jetty-io-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.fill(SocketConnector.java:209) [jetty-server-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.dcache.util.JettyGSIConnector$GsiConnection.fill(JettyGSIConnector.java:527) [dcache.jar:na]
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:289) [jetty-http-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:214) [jetty-http-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.eclipse.jetty.server.HttpConnection.handle(HttpConnection.java:411) [jetty-server-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.eclipse.jetty.server.bio.SocketConnector$ConnectorEndPoint.run(SocketConnector.java:241) [jetty-server-7.4.2.v20110526.jar:7.4.2.v20110526]
        at org.dcache.util.JettyGSIConnector$GsiConnection.run(JettyGSIConnector.java:550) [dcache.jar:na]
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:529) [jetty-util-7.4.2.v20110526.jar:7.4.2.v20110526]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_24]


The issue, as far as I understand it, is that StreamEndPoint.fill was
changed to call shudownInput() on the ConnectorEndPoint. Jetty's SSL
implementation will close the socket as a result. Our GSI
ConnectorEndpoint doesn't.

This patch simply copies the corresponding pieces from Jetty's
implementation.

It also incorporates earlier changes for shutdownOutput().

Target: trunk
Request: 1.9.13
Acked-by: Jan Schaefer <jan.schaefer@desy.de>
Patch: http://rb.dcache.org/r/3596/