Define default transaction isolation level for databases
BoneCP doesn't remember the default isolation level of the
actual Connection. Instead it injects a configured default,
or leaves the setting untouched if not defined. The latter
means that the isolation level is unpredictable if it is
changed by some code and then the connection is recycled
by some other code.

In the SRM this leads to errors like:

16 Oct 2013 22:33:37 (SRM-sisyphus) [131.169.72.212:51026 3Lg:9:srm2:prepareToPut] Please report this failure to support@dcache.org
org.springframework.dao.CannotSerializeTransactionException: PreparedStatementCallback; SQL [UPDATE srmrequestcredentials SET creationtime=?, credentialname=?, role=?,  numberofusers=?, delegatedcredentials=?, credentialexpiration=? where id=? ]; ERROR: could not serialize access due to concurrent update; nested exception is org.postgresql.util.PSQLException: ERROR: could not serialize access due to concurrent update
	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:273) ~[spring-jdbc-3.2.3.RELEASE.jar:3.2.3.RELEASE]

This error is caused by the isolation level being higher than
expected.

This patch sets the default to READ_COMMITTED. This matches
the PostgreSQL default, which is what our code is developed
for.

Target: trunk
Require-notes: no
Require-book: no
Acked-by: Dmitry Litvintsev <litvinse@fnal.gov>
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: http://rb.dcache.org/r/6122/