dcap: fix "make rpm" target finding unpackaged files.
The end of the "make rpm" target breaks due to 

Checking for unpackaged file(s): /usr/lib/rpm/check-files /var/tmp/dcache-dcap-root
error: Installed (but unpackaged) file(s) found:
   /opt/d-cache/dcap/bin/dcap_url-test

So I add this binary to the dcache-dcap-tests-2.??.0-0.x86_64.rpm

Acked-by: Paul
http://rb.dcache.org/r/1681/