webdav: fix bean creation in webdav.xml for spnego handler
The master build deployement was broken by the
commit: 159c42257703d227583268b59dbd3066ec9570a9

(System) [] Failure at startup: (666) URL
[file:/usr/share/dcache/services/webdav.batch]: line 120: (3) Invalid
bean definition with name 'spnegohandler' defined in class path resource
[org/dcache/webdav/webdav.xml]: Could not resolve placeholder
'webdav.authz.spnego.properties-file' in string value
"${webdav.authz.spnego.properties-file}"; nested exception is
java.lang.IllegalArgumentException: Could not resolve placeholder
'webdav.authz.spnego.properties-file' in string value
"${webdav.authz.spnego.properties-file}"

fixed the property name causing the problem

Ticket:
Target: trunk
Require-book: no
Require-notes: no
Patch: