core: describe missing FileAttribute in PoolManager message
Motivation:

We have had reports of the following stack-trace:

11 Feb 2019 16:51:21 (RemoteTransferManager) \[...\] Uncaught exception in thread pool-25-thread-1862
java.lang.IllegalArgumentException: Required attributes are missing.
        at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122) ~\[guava-20.0.jar:na\]
        at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:77) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at diskCacheV111.vehicles.PoolMgrSelectReadPoolMsg.<init>(PoolMgrSelectReadPoolMsg.java:62) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at diskCacheV111.services.TransferManagerHandler.selectPool(TransferManagerHandler.java:448) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at diskCacheV111.services.TransferManagerHandler.storageInfoArrived(TransferManagerHandler.java:442) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at diskCacheV111.services.TransferManagerHandler.success(TransferManagerHandler.java:270) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at org.dcache.cells.AbstractMessageCallback.success(AbstractMessageCallback.java:32) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at org.dcache.cells.CellStub.lambda$addCallback$0(CellStub.java:516) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at org.dcache.util.CDCExecutorServiceDecorator$WrappedRunnable.run(CDCExecutorServiceDecorator.java:149) ~\[dcache-core-3.2.41.jar:3.2.41\]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~\[na:1.8.0_191\]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~\[na:1.8.0_191\]
        at java.lang.Thread.run(Thread.java:748) ~\[na:1.8.0_191\]

Unfortunately, this message does not describe which attributes are
missing, making it harder to diagnose this problem.

Modification:

Include the set of missing attributes in the logged message.

Result:

More diagnostic information to help track down a bug in transfermanager
(and elsewhere).

Target: master
Requires-notes: no
Requires-book: no
Patch: https://rb.dcache.org/r/11542/
Acked-by: Marina Sahakyan