testing: fix classpath
Since v4.4, junit has supported the assertThat methods.  The junit jar 
file also includes some basic matchers.  The problem is that these use 
the same package namespace as hamcrest (org.hamcrest).  This means 
that, if a project includes junit and hamcrest jar files then it's 
unspecified which implementation of assertThat will be used: the one 
from junit or the one from hamcrest.

Somehow this hasn't been a problem until now, but today I'm seeing 
tests failing with errors like:

java.lang.NoSuchMethodError: org.hamcrest.Matcher.describeMismatch(Ljava/lang/Object;Lorg/hamcrest/Description;)V
        at org.hamcrest.core.IsCollectionContaining.matchesSafely(IsCollectionContaining.java:31)
        at org.hamcrest.core.IsCollectionContaining.matchesSafely(IsCollectionContaining.java:14)
        at org.hamcrest.TypeSafeDiagnosingMatcher.matches(TypeSafeDiagnosingMatcher.java:54)
        at org.junit.Assert.assertThat(Assert.java:772)
[...etc...]

The problem is fixed by using junit-dep: a version of junit that 
doesn't include the hamcrest matchers.

paul@zitpcx6184:~$ jar tf ~/.m2/repository/junit/junit/4.10/junit-4.10.jar > /tmp/junit
paul@zitpcx6184:~$ jar tf ~/.m2/repository/junit/junit-dep/4.10/junit-dep-4.10.jar >/tmp/junit-dep
paul@zitpcx6184:~$ diff -u /tmp/junit{,-dep}
--- /tmp/junit  2012-08-27 18:27:18.000000000 +0200
+++ /tmp/junit-dep      2012-08-27 18:27:23.000000000 +0200
@@ -6,9 +6,6 @@
 junit/runner/
 junit/textui/
 org/
-org/hamcrest/
-org/hamcrest/core/
-org/hamcrest/internal/
 org/junit/
 org/junit/experimental/
 org/junit/experimental/categories/
@@ -66,29 +63,6 @@
 junit/textui/ResultPrinter.class
 junit/textui/TestRunner.class
 junit/textui/package-info.class
-org/hamcrest/BaseDescription.class
-org/hamcrest/BaseMatcher.class
[..etc..]
-org/hamcrest/internal/SelfDescribingValueIterator.class
-org/hamcrest/package.html
 org/junit/After.class
 org/junit/AfterClass.class
 org/junit/Assert.class
paul@zitpcx6184:~$ 

Target: trunk
Require-book: no
Require-notes: no
Patch: http://rb.dcache.org/r/4846/
Acked-by: Gerd Behrmann