pool: Fixed IllegalStateException in case of xrootd mover timeout
A mover may be forcefully terminated by the JTM or the admin. When this happens
the file channel will be closed. This can cause exceptions like the following to
be generated:

04 Apr 2012 08:17:46 (csc_fi_006) [Xrootd-gonzo PoolDeliverFile 00005EC97A43FD8B46F3A77281A40E7821C2] Processing write[handle=0,offset=260046848,length=8388608] failed due to a bug
java.lang.IllegalStateException: Handle is closed
at org.dcache.pool.repository.v5.WriteHandleImpl.allocate(WriteHandleImpl.java:157) ~[dcache-core-2.1.2.jar:2.1.2]
at org.dcache.xrootd.pool.XrootdProtocol_3.preallocate(XrootdProtocol_3.java:556) ~[dcache-core-2.1.2.jar:2.1.2]
at org.dcache.xrootd.pool.WriteDescriptor.write(WriteDescriptor.java:79) ~[dcache-core-2.1.2.jar:2.1.2]
at org.dcache.xrootd.pool.XrootdPoolRequestHandler.doOnWrite(XrootdPoolRequestHandler.java:487) ~[dcache-core-2.1.2.jar:2.1.2]
at org.dcache.xrootd.core.XrootdRequestHandler.requestReceived(XrootdRequestHandler.java:94) [xrootd4j-1.0.1.jar:1.0.1]
at org.dcache.xrootd.core.XrootdRequestHandler.messageReceived(XrootdRequestHandler.java:54) [xrootd4j-1.0.1.jar:1.0.1]
at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:100) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:48) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:275) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:80) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:783) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.handler.execution.ChannelEventRunnable.run(ChannelEventRunnable.java:69) [netty-3.2.7.Final.jar:na]
at org.jboss.netty.handler.execution.OrderedMemoryAwareThreadPoolExecutor$ChildExecutor.run(OrderedMemoryAwareThreadPoolExecutor.java:316) [netty-3.2.7.Final.jar:na]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_31]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_31]
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_31]

This particular exception is caused by a missing exception handler in doOnWrite,
however there is a more generic issue in that the file descriptor classes check
whether the channel is open and throw IllegalStateException if it is not. This
cannot work as the channel may be closed after the check and before the IO
operation is performed. The IO operation would then fail with a
ChannelClosedException.

The patch addresses this problem by

a) Remove the checks in the file descriptor for whether the file channel is open.
Instead we embrace that the FileChannel will throw ChannelClosedException if it
is no longer open.

b) Change/add the exception handlers to process ChannelClosedException.

c) Allow FileDescriptor.getChannel to return a closed channel, thus allowing
XrootdPoolRequestHandler to deregister itself from the NettyServer even when
the channel is closed.

Release notes: Fixed several race conditions in the xrootd mover that would be
triggered when the mover is killed. The symptoms of the race condition were
stack traces in the pool log.

Target: trunk
Request: 2.3
Request: 2.2 (patch will be attached to merge request)
Request: 1.9.12 (patch will be attached to merge request)
Ticket: http://rt.dcache.org/Ticket/Display.html?id=7173
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: http://rb.dcache.org/r/4643/