libraries: bump netty-tcnative version to 2.0.48
Motivation:

A recent commit (7a7b5dce1b) merged a pull-request that bumped the netty
version from v4.1.59 to v4.1.71.  This new version of Netty broke API
compatibility.  It did this by updating ReferenceCountedOpenSslContext
so that class now calls the SSLContext#setCurvesList method.

The SSLContext class from the current version of netty-tcnative
(v2.0.39) does not support this method.  Support for setting the curves
list was only added with v2.0.42.

Therefore, when dCache starts up, we see errors like:

```
02 Feb 2022 20:21:55 (Xrootd-sprocket) [] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creatin
g bean with name 'server' defined in class path resource [org/dcache/xrootd/door/xrootd.xml]: Cannot resolve reference to bean 'ssl-handler-factories' while setting bean property 'SSLHandlerFact
ories'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'ssl-handler-factories': FactoryBean threw exception on object creation; nes
ted exception is java.lang.NoSuchMethodError: 'boolean io.netty.internal.tcnative.SSLContext.setCurvesList(long, java.lang.String[])'
02 Feb 2022 20:21:55 (System) [] Thread Thread[main,5,main] died
java.lang.NoSuchMethodError: 'boolean io.netty.internal.tcnative.SSLContext.setCurvesList(long, java.lang.String[])'
        at io.netty.handler.ssl.ReferenceCountedOpenSslContext.<init>(ReferenceCountedOpenSslContext.java:389)
        at io.netty.handler.ssl.OpenSslContext.<init>(OpenSslContext.java:45)
[...]
```

Modification:

Update netty-tcnatve to what is currently latest version.

Result:

An unreleased regression was fixed.

Target: master
Requires-notes: no
Requires-book: no
Patch: https://rb.dcache.org/r/13415/
Acked-by: Albert Rossi