dcache: Creating multiple KafkaProducer instances results in 'Too many open files'
Motivation

For dcap and ftp dorrs for each transfer was created new Kafka producer.

As a result first Server was shutdown with the following IO exception

java.io.IOException: Too many open files
at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
at
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
at
sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
at kafka.network.Acceptor.accept(SocketServer.scala:452)
at kafka.network.Acceptor.run(SocketServer.scala:395)
at java.lang.Thread.run(Thread.java:748)

The reason is that  it reaches its  limit for  open files for the server.
 The default setting of 1024 for the maximum number of open files on most Unix-like systems is insufficient.

Second issue was that the for each new producer new connnection was oppened which resulted in  gradual
increase in CPU load and in that event the doors were shutdown

Modifications

	Kafka Producers are now flushed and closed when destroy or close methods are called.

for xrootd, webdav, nfs and pool  autoFlush configuration is added to flush producer after send.

Target: master
Request: 4.2
Require-notes: yes
Require-book: no
Patch: https://rb.dcache.org/r/11194/
Acked-by: Tigran