cells: better handling of rogue domains with badly formatted dCache versions
Motivation:

Reports of stack-trace like:

    25 Jul 2017 15:08:13 (l-AAVVKQzyFMg) [130.199.148.177:45808] Bug detected in dCache; please report this to <support@dcache.org>
    java.lang.NumberFormatException: Invalid dCache version: undefined
            at dmg.util.Releases.getRelease(Releases.java:38) ~[cells-3.0.11.jar:3.0.11]
            at dmg.cells.nucleus.CellDomainInfo.getRelease(CellDomainInfo.java:47) ~[cells-3.0.11.jar:3.0.11]
            at dmg.cells.network.LocationMgrTunnel.handshake(LocationMgrTunnel.java:172) ~[cells-3.0.11.jar:3.0.11]
            at dmg.cells.network.LocationMgrTunnel.starting(LocationMgrTunnel.java:109) ~[cells-3.0.11.jar:3.0.11]
            at dmg.cells.nucleus.CellAdapter.prepareStartup(CellAdapter.java:722) ~[cells-3.0.11.jar:3.0.11]
            at dmg.cells.nucleus.CellNucleus.doStart(CellNucleus.java:918) [cells-3.0.11.jar:3.0.11]
            at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$5(CellNucleus.java:751) [cells-3.0.11.jar:3.0.11]
            at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:108) ~[guava-19.0.jar:na]
            at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:41) ~[guava-19.0.jar:na]
            at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:77) ~[guava-19.0.jar:na]
            at org.dcache.util.BoundedExecutor$Worker.run(BoundedExecutor.java:251) ~[dcache-common-3.0.11.jar:3.0.11]
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
            at dmg.cells.nucleus.CellNucleus.lambda$wrapLoggingContext$4(CellNucleus.java:742) [cells-3.0.11.jar:3.0.11]
            at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_121]

Modification:

Since the problem is due (in part) to forgetting about an unchecked
exception, this patch switches NumberFormatException to a checked
exception as quickly as possible.

It also adds explicit handling of this checked exception that should
prevent dCache logging a stack-trace in this case.

Result:

One less stack-trace.

Target: master
Require-notes: yes
Require-book: no
Target: master
Request: 3.1
Request: 3.0
Request: 2.16