xrootd: Allow simultaneous authn and authz plugins and remove bucket size limit
Those limitations in the code appear to be arbitrary. The limitation 
on simultaneous use of an authn and authz plugin was already removed 
in subsequent releases.

Release notes: Removed a restriction that prevented an xrootd 
authentication plugin and an xrootd authorization plugin to be used at 
the same time. Removed a limitation on xrootd authentication bucket 
size. The limit would have resulted in error messages like "Caused by: 
java.io.IOException: Encountered a bucket with length 11088. Maximum 
allowed bucket length 10000".

Target: 1.9.12
Patch: http://rb.dcache.org/r/4599
Merge-request: http://rt.dcache.org/Ticket/Display.html?id=7231
Signed-off-by: Gerd Behrmann
Acked-by: Paul Millar