ftp: add work-around for broken Globus FTP client
Motivation:

On third-party transfers, Globus issues the QUIT command to the
destination without waiting for the response.  This introduces a
race-condition.  Depending on the arrival order of packets, this
can lead to dCache logging a message like:

    java.io.IOException: Connection reset by peer

Modification:

Add a work-around where the output from the QUIT command is suppressed
if the client identifies itself as globus-url-copy.

Result:

No more errors being logged.

Target: master
Require-notes: yes
Require-book: no
Patch: https://rb.dcache.org/r/10551/
Acked-by: Tigran Mkrtchyan