srm: Remove duplicate SURLs in bringonline and get requests
We have observed that Atlas is sometimes duplicating SURLs in requests. One may
argue that such requests are invalid, but on the other hand there is nothing in
the SRM spec. saying that they are. Semantically, such duplicates are no
different from just submiting the SURL once.

Pin manager however in some cases fails with a nasty stack trace when the same
SURL is requested twice with the same request ID. This happens when the two
requests are created concurrently as pin manager fails to isolate those
operations from each other. Due to issues in how the PostgreSQL JDBC driver is
constructed and how DataNucleus treats SQLExceptions, the actual primary key
constraint violation is lost, making it difficult for pin manager to recover
from this situation. We could bump up the transaction isolation, but we would
need to use SERIABLE.

Instead this patch chooses the pragmatic path and eliminates the duplicate SURLs
in the SRM.

The admin visible stack trace caused by this bug looked something like this:

03 May 2015 10:16:26 (PinManager) [] Uncaught exception in thread pool-4-thread-13
org.springframework.orm.jdo.JdoResourceFailureException: Exception thrown flushing changes to datastore; nested exception is javax.jdo.JDODataStoreException: Exception thrown flushing changes to datastore
NestedThrowables:
java.sql.BatchUpdateException: Batch entry 0 INSERT INTO "pins" ("created_at","expires_at","gid","pnfsid","pool","request_id","state","sticky","uid","id") VALUES ('2015-05-03 10:16:25.999000 +02:00:00','2015-05-03 12:17:25.999000 +02:00:00',5001,'0000416D7C9E3D78467CA897BA9872E8BBE2',NULL,'-1730570248','PINNING','PinManager-1f044020-a7f7-4d3c-bdef-377f864f2ae4',5001,34575144) was aborted.  Call getNextException to see the cause.

Target: trunk
Request: 2.12
Request: 2.11
Request: 2.10
Require-notes: yes
Require-book: no
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: https://rb.dcache.org/r/8198/