PoolManager: Fix compatibility with migration module
01 Mar 2011 13:58:11 (PoolManager) [] Uncaught exception in thread Thread-227
dmg.cells.nucleus.SerializationException: Failed to serialize object because the object is not serializable (this is usually a bug)
        at dmg.cells.nucleus.CellMessage._originalToStream(CellMessage.java:191) ~[cells.jar:na]
        at dmg.cells.nucleus.CellMessage.<init>(CellMessage.java:142) ~[cells.jar:na]
        at dmg.cells.nucleus.CellGlue.sendMessage(CellGlue.java:509) ~[cells.jar:na]
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:370) ~[cells.jar:na]
        at dmg.cells.nucleus.CellNucleus.sendMessage(CellNucleus.java:348) ~[cells.jar:na]
        at dmg.cells.nucleus.CellAdapter.sendMessage(CellAdapter.java:427) ~[cells.jar:na]
        at org.dcache.cells.AbstractCell.sendReply(AbstractCell.java:814) ~[dcache.jar:na]
        at org.dcache.cells.AbstractCell.messageArrived(AbstractCell.java:916) ~[dcache.jar:na]
        at org.dcache.cells.UniversalSpringCell.messageArrived(UniversalSpringCell.java:294) ~[dcache.jar:na]
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:962) ~[cells.jar:na]
        at dmg.cells.nucleus.CellNucleus$DeliverMessageTask.innerRun(CellNucleus.java:1083) ~[cells.jar:na]
        at dmg.cells.nucleus.CellNucleus$AbstractNucleusTask.run(CellNucleus.java:981) ~[cells.jar:na]
        at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_24]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_24]
        at dmg.cells.nucleus.CellNucleus$1.run(CellNucleus.java:654) [cells.jar:na]
        at java.lang.Thread.run(Thread.java:662) [na:1.6.0_24]
Caused by: java.io.NotSerializableException: com.google.common.collect.Collections2$TransformedCollection
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1164) ~[na:1.6.0_24]
        at java.io.ObjectOutputStream.defaultWriteFields(ObjectOutputStream.java:1518) ~[na:1.6.0_24]
        at java.io.ObjectOutputStream.writeSerialData(ObjectOutputStream.java:1483) ~[na:1.6.0_24]
        at java.io.ObjectOutputStream.writeOrdinaryObject(ObjectOutputStream.java:1400) ~[na:1.6.0_24]
        at java.io.ObjectOutputStream.writeObject0(ObjectOutputStream.java:1158) ~[na:1.6.0_24]
        at java.io.ObjectOutputStream.writeObject(ObjectOutputStream.java:330) ~[na:1.6.0_24]
        at dmg.cells.nucleus.CellMessage._originalToStream(CellMessage.java:186) ~[cells.jar:na]
        ... 15 common frames omitted

Target: trunk
Request: 1.9.12
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: http://rb.dcache.org/r/3121/