pool: Fix NPE in migration module
05 Sep 2011 15:26:20 (hpc2n_umu_se_042) [] java.lang.RuntimeException: Bug detected
java.lang.RuntimeException: Bug detected
at org.dcache.pool.migration.Task$Callback$1.run(Task.java:514) ~[dcache.jar:na]
at org.dcache.pool.migration.Task$LoggingTask.run(Task.java:560) ~[dcache.jar:na]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441) [na:1.6.0_26]
at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303) [na:1.6.0_26]
at java.util.concurrent.FutureTask.run(FutureTask.java:138) [na:1.6.0_26]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:98) [na:1.6.0_26]
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:206) [na:1.6.0_26]
at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886) [na:1.6.0_26]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908) [na:1.6.0_26]
at java.lang.Thread.run(Thread.java:662) [na:1.6.0_26]
Caused by: java.lang.reflect.InvocationTargetException: null
at sun.reflect.GeneratedMethodAccessor17.invoke(Unknown Source) ~[na:na]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25) ~[na:1.6.0_26]
at java.lang.reflect.Method.invoke(Method.java:597) ~[na:1.6.0_26]
at org.dcache.pool.migration.Task$Callback$1.run(Task.java:502) ~[dcache.jar:na]
... 9 common frames omitted
Caused by: java.lang.NullPointerException: null
at org.dcache.pool.migration.ProportionalPoolSelectionStrategy.select(ProportionalPoolSelectionStrategy.java:150) ~[dcache.jar:na]
at org.dcache.pool.migration.Task.selectPool(Task.java:216) ~[dcache.jar:na]
at org.dcache.pool.migration.Task.initiateCopy(Task.java:298) ~[dcache.jar:na]
at org.dcache.pool.migration.TaskContext$TASK_Default$TASK_InitiatingCopy.Entry(TaskContext.java:896) ~[dcache.jar:na]
at org.dcache.pool.migration.TaskContext$TASK_Default$TASK_GettingLocations.query_success(TaskContext.java:618) ~[dcache.jar:na]
at org.dcache.pool.migration.TaskContext.query_success(TaskContext.java:204) ~[dcache.jar:na]
... 13 common frames omitted


Triggered by cost module not having up to date information about a pool.
In that case the PoolCostInfo property of PoolManagerPoolInformation is
null.

The patch fixes the above problem and also makes the migration module
more robust against such bugs.

Target: trunk
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: http://rb.dcache.org/r/3689/