chimera: Make FsSqlDriver#addInodeLocation PostgreSQL compatible
Motivation:

PostgreSQL looses the type information in the relatively complex insert
statement to emulate an 'upsert'. This results in:

02 Dec 2015 07:40:05 (PnfsManager) [door:NFS-dcache-lab007:AAUl6ZLhaRg dcache-lab001-A PnfsAddCacheLocation 0000B45273530BA54F60B6C447B82B4EB6A4] Exception in addCacheLocation {}
org.dcache.chimera.IOHimeraFsException: PreparedStatementCallback; bad SQL grammar [INSERT INTO t_locationinfo (SELECT * FROM (VALUES (?,?,?,?,?,?,?)) v WHERE NOT EXISTS (SELECT 1 FROM t_locationinfo WHERE ipnfsid=? AND itype=? AND ilocation=?))]; nested exception is org.postgresql.util.PSQLException: ERROR: column "ictime" is of type timestamp with time zone but expression is of type text

Modification:

Make a simpler PostgreSQL specific expression. This relies on a having a
select without from which isn't part of the SQL standard and not supported
by H2 and HSQLDB.

Result:

Should work with PostgreSQL.

Target: trunk
Request: 2.14
Require-notes: no
Require-book: no
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: https://rb.dcache.org/r/8838/