chimera: Do not ignore DuplicateKeyExceptions
Motivation:

Chimera in several places silently ignores DuplicateKeyException, expecting
these conflicts to be normal behaviour. PostgreSQL however doesn't allow any
further queries once a transaction generates this error, thus some multi-query
operations will fail now that we run them in a single transaction.

Modification:

There are two possible solutions: Use save points at the cost of additional
server round trips, or avoid the duplicate key exceptions. The patch chooses
the latter approach.

Since different databases have different syntax for the required "upsert"
operation, we instead use a pattern already used by the chimera postgresql
driver: insert into x (select * from (values (?,?,?)) v where not exists
(select 1 from x where key=?); the syntax is slightly adjusted from previous
uses to be standard compliant. This is used  in the chimera base SQL driver,
removing the need to ignore duplication errors.

The PostgreSQL 9.5 driver overrides this to use the new 'on conflict' syntax.

Result:

Avoids

02 Dec 2015 03:52:12 (PnfsManager) [door:NFS-dcache-lab007:AAUl5mPoL6A dcache-lab001-A PnfsSetFileAttributes 00008DA7B31B331743A3AB401F958A11F5CF] Exception in setFileAttributes: {}
org.dcache.chimera.IOHimeraFsException: PreparedStatementCallback; uncategorized SQLException for SQL []; SQL state [25P02]; error code [0]; ERROR: current transaction is aborted, commands ignored until end of transaction block; nested exception is org.postgresql.util.PSQLException: ERROR: current transaction is aborted, commands ignored until end of transaction block

Also gets rid of warnings in the postgresql log about duplicate key violations.

Target: trunk
Require-notes: yes
Require-book: no
Request: 2.14
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Patch: https://rb.dcache.org/r/8837/
(cherry picked from commit 4f222780f9917f912cc204e356ba7c3b3b5d5583)