cells: Log bugs in command processing
CommandInterpreter rethrows exceptions thrown by a command as a
CommandThrowableException. This patch makes certain that such exceptions
other than IllegalArgumentException are logged with a stack trace.

The patch doesn't actually add any new log entries: Instead it makes
certain that Errors and RuntimeExceptions are classified as such by
CommandInterpreter: Rather than hiding those critical errors or bugs
inside a CommandThrowableException, these Throwables are propagated to
the caller.

This has the advantage that:

- OOM and other VM errors reach the uncaught exception handler and will
  cause a domain shutdown

- Both Error and RuntimeExceptions are logged by the uncaught exception
  handler

- The fix works for both batch files and string commands send to the
  cell.

Notice that the patch changes one crucial aspect of error processing:
Bugs (i.e. RuntimeExceptions) will cause the BatchCell to terminate
processing; it will however not cause it to shut down the domain. This
may be considered a feature, as it avoids an infinite restart loop. This
can however be changed by catching RuntimeException in BatchCell and
call System.exit like we do for some CommandExitExceptions.

Testing Done:

I added the following to CellShell.

    public String ac_debug(Args args)
    {
        if (args.getOpt("null") != null) {
            throw new NullPointerException();
        }
        if (args.getOpt("error") != null) {
            throw new Error();
        }
        return "";
    }


Sending 'debug -null' and 'debug -error' caused the stack traces to be 
logged. Adding the commands to a batch file had the same effect.


I also tested the create method: In System@dCacheDomain I ran

[dcache-vm] (System@dCacheDomain) admin > create diskCacheV111.srm.dcache.Storage test8 "-jdbcUrl=sds -jdbcDriver=sds -dbUser=srmdcache -dbPass=test -pgPass=/tmp/x"
java.lang.NullPointerException


The log file now correctly contained the stack trace: 

14 Jan 2010 13:12:47 (System) [] Uncaught exception in thread Messages
java.lang.NullPointerException
        at java.util.Hashtable.put(Hashtable.java:394)
        at org.dcache.auth.persistence.AuthRecordPersistenceManager.<init>(AuthRecordPersistenceManager.java:58)
        at diskCacheV111.srm.dcache.Storage.<init>(Storage.java:757)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
        at dmg.cells.nucleus.CellGlue._newInstance(CellGlue.java:161)
        at dmg.cells.nucleus.CellNucleus.createNewCell(CellNucleus.java:827)
        at dmg.cells.nucleus.CellShell.ac_create_$_2_3(CellShell.java:706)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at dmg.util.CommandInterpreter.execute(CommandInterpreter.java:591)
        at dmg.util.CommandInterpreter.command(CommandInterpreter.java:477)
        at dmg.cells.nucleus.CellShell.objectCommand2(CellShell.java:140)
        at dmg.cells.nucleus.SystemCell.messageArrived(SystemCell.java:229)
        at dmg.cells.nucleus.CellAdapter.messageArrived(CellAdapter.java:989)
        at dmg.cells.nucleus.CellNucleus.run(CellNucleus.java:539)
        at dmg.cells.nucleus.CellNucleus$1.run(CellNucleus.java:611)
        at java.lang.Thread.run(Thread.java:619)


This was with 1.9.5-10. Trying the same with trunk I get:

[dcache-vm] (System@dCacheDomain) admin > create diskCacheV111.srm.dcache.Storage test8 "-jdbcUrl=sds -jdbcDriver=sds -dbUser=srmdcache -dbPass=test -pgPass=/tmp/x"
dmg.util.CommandThrowableException: (3) java.sql.SQLException: could not get password from '/tmp/x' for  hostname: 'localhost' ,port: 5432 ,database: 'sds' and username: 'srmdcache'  from ac_create_$_2_3

and no stack trace in the log file (as expected as this is no 
RuntimeException).

Target: trunk
Target: 1.9.6
Target: 1.9.5
Ticket: #5329
Patch: http://rb.dcache.org/r/1336/
Acked-by: Timur Perelmutov <timur@fnal.gov>