Fix serialization of cache class in FileAttributes
To maintain backwards compatibility, cache class serialization is treated in a
special way. As a side effect, serializing FileAttributes clears it CACHECLASS
attribute when being serialized, thus after sending FileAttributes to another
cell, the original object is corrupted. This leads to the following error:

16 Mar 2015 10:26:16 (PoolManager) [Jrs:11946394:srm2:bringOnline:-1776876581:-1776876578 PinManager PoolMgrSelectReadPool 0000FD7EE4F955D0440B936D7B605C89FAAD] [stage] contact support@dcache.org
java.lang.IllegalStateException: Attribute is not defined: CACHECLASS
        at org.dcache.vehicles.FileAttributes.guard(FileAttributes.java:171) ~[dcache-vehicles-2.12.0.jar:2.12.0]
        at org.dcache.vehicles.FileAttributes.getCacheClass(FileAttributes.java:457) ~[dcache-vehicles-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.PoolSelectionUnitV2.match(PoolSelectionUnitV2.java:440) ~[dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.PoolMonitorV5$PnfsFileLocation.match(PoolMonitorV5.java:143) ~[dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.PoolMonitorV5$PnfsFileLocation.selectStagePool(PoolMonitorV5.java:366) ~[dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.askForStaging(RequestContainerV5.java:2005) [dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.stateEngine(RequestContainerV5.java:1561) [dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.stateLoop(RequestContainerV5.java:1147) [dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler.access$1700(RequestContainerV5.java:689) [dcache-core-2.12.0.jar:2.12.0]
        at diskCacheV111.poolManager.RequestContainerV5$PoolRequestHandler$RunEngine.run(RequestContainerV5.java:1078) [dcache-core-2.12.0.jar:2.12.0]
        at org.dcache.util.FireAndForgetTask.run(FireAndForgetTask.java:31) [dcache-core-2.12.0.jar:2.12.0]
        at org.dcache.util.CDCExecutorServiceDecorator$1.run(CDCExecutorServiceDecorator.java:104) [dcache-core-2.12.0.jar:2.12.0]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

The patch makes minor adjustments to required attribute handling in related
parts of the code (done to exclude other sources of the same problem).

Target: trunk
Request: 2.12
Require-notes: yes
Require-book: no
Acked-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>
Acked-by: Paul Millar <paul.millar@desy.de>
Patch: https://rb.dcache.org/r/7974/