CellGlue: Bug fix in CellGlue
Motivation:
When the 'set classloader' command is use to set a cell, for example (System@dCacheDomain) admin >  set classloader me.you topo@dCacheDomain you get:
java.lang.IllegalArgumentException: Provider type not supported : cells

This is cause by the mismatch between the spelling (cell and cells) in the if condition and switch case block respectively.

Modification:
Deletion of 's' in the case block for 'cell'

Result:
The command behave as expected, see below for the result after the fix
    (System@dCacheDomain) admin >  show classloader
    *                   CDP=System
    *.me                none
    *.me.you            CDP0;Cell=SystemCellPath=[>topo@dCacheDomain]

Ticket: 8461
Acked-by: Paul Millar
Target: trunk
Require-book: no
Require-notes: no